# Generated by Django 4.2.1 on 2023-05-30 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("l1o", "0003_alter_matches_away_team_alter_matches_division_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Divisions",
            new_name="Division",
        ),
        migrations.RenameModel(
            old_name="Matches",
            new_name="Match",
        ),
        migrations.RenameModel(
            old_name="Teams",
            new_name="Team",
        ),
    ]
