# Generated by Django 4.2.1 on 2023-06-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("l1o", "0006_alter_match_division_alter_team_division"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="match",
            name="away_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_score",
            field=models.IntegerField(default=0),
        ),
    ]
