# Generated by Django 4.2.1 on 2023-06-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("l1o", "0007_match_is_completed_alter_match_away_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="e2e_id",
            field=models.IntegerField(unique=True),
        ),
    ]
