# Generated by Django 4.2.1 on 2023-05-30 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("l1o", "0002_divisions_matches_teams_delete_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matches",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_matches",
                to="l1o.teams",
            ),
        ),
        migrations.AlterField(
            model_name="matches",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_division",
                to="l1o.divisions",
            ),
        ),
        migrations.AlterField(
            model_name="matches",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_matches",
                to="l1o.teams",
            ),
        ),
        migrations.AlterField(
            model_name="teams",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_division",
                to="l1o.divisions",
            ),
        ),
    ]
