# Generated by Django 4.2.1 on 2023-06-03 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("l1o", "0004_rename_divisions_division_rename_matches_match_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="scheduled_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
